#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def switch_sn_inv(info, params):

        serialnum = ""
        if len(info[0]) >= 1:
                if info[0][0][0] != "":
                        serialnum = info[0][0][0]
                else:
                        serialnum = info[0][0][1]
        else:
                serialnum = "NOTFOUND"

                modelname = ""
        if len(info[1]) >= 1:
                if info[1][0][0] != "":
                        modelname = info[1][0][0]
                else:
                        modelname = info[1][0][1]
        else:
                modelname = "NOTFOUND"


        node = inv_tree("hardware.system.")
        node["PhysicalSerialNum"] = serialnum
        node["PhysicalModelName"] = modelname

inv_info['switch_sn'] = {
    "inv_function" : switch_sn_inv,
    'snmp_info':               [(".1.3.6.1.2.1.47.1.1.1.1.11",  ["1", "1001"]), # entPhysicalSerialNum
                                (".1.3.6.1.2.1.47.1.1.1.1.13",  ["1", "1001"]), # entPhysicalModelName
    ],
    'snmp_scan_function':      lambda oid: oid(".1.3.6.1.2.1.1.1.0") != None,
}