#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


#inetCidrRouteTable ipCidrRouteTable ipRouteTable

def get_ipRouteTable(ipRouteTable):
	ipRouteTable_decode = { 		
		"1":"ipRouteDest",
		"2":"ipRouteIfIndex",
		"3":"ipRouteMetric1",
		"4":"ipRouteMetric2",
		"5":"ipRouteMetric3",
		"6":"ipRouteMetric4",
		"7":"ipRouteNextHop",
		"8":"ipRouteType",
		"9":"ipRouteProto",
		"10":"ipRouteAge",
		"11":"ipRouteMask",
		"12":"ipRouteMetric5",
		"13":"ipRouteInfo"}
	ipRouteProto_decode = {
		"1":"other",
		"2":"local",
		"3":"netmgmt",
		"4":"icmp",
		"5":"egp",
		"6":"ggp",
		"7":"hello",
		"8":"rip",
		"9":"is-is",
		"10":"es-is",
		"11":"ciscoIgrp",
		"12":"bbnSpfIgp",
		"13":"ospf",
		"14":"bgp"}
        ipRouteType_decode = {
                "1":"other",
                "2":"invalid",
                "3":"direct",
                "4":"indirect"}
	
	ipRouteTable_dict = {}
	for oid, value in ipRouteTable:
		oid_type =  oid.split(".")[0]
		oid_ip   =  ".".join(oid.split(".")[1:])

		if oid_ip not in ipRouteTable_dict.keys():
			ipRouteTable_dict[oid_ip] = {}

		if ipRouteTable_decode[oid_type] == "ipRouteMask":
			mask_cidr = str(sum([bin(int(x)).count('1') for x in value.split('.')]))
			ipRouteTable_dict[oid_ip].update( {"ipRouteMask_cidr": mask_cidr} )
			ipRouteTable_dict[oid_ip].update( {ipRouteTable_decode[oid_type]:value} )

		elif ipRouteTable_decode[oid_type] == "ipRouteProto": 
			ipRouteProto_desc = ipRouteProto_decode[value]
			ipRouteTable_dict[oid_ip].update( {ipRouteTable_decode[oid_type]:ipRouteProto_desc} )

                elif ipRouteTable_decode[oid_type] == "ipRouteType": 
                        ipRouteType_desc = ipRouteType_decode[value]
                        ipRouteTable_dict[oid_ip].update( {ipRouteTable_decode[oid_type]:ipRouteType_desc} )
		else:
			ipRouteTable_dict[oid_ip].update( {ipRouteTable_decode[oid_type]:value} )
	
	return ipRouteTable_dict


def get_if_desc(port_info):
	ifDesc_dict = {}

	for interface in port_info:
		if_index = str(interface[0])
		if_desc  = interface[1]
		ifDesc_dict[if_index] = if_desc

	return ifDesc_dict


	

def inv_switch_ipRoute(info, params):

    	port_info, ipRouteTable = info
	ipRouteTable_dict = get_ipRouteTable(ipRouteTable)
	ifDesc_dict = get_if_desc(port_info)

	routes = inv_tree("networking.switch_ipRoute:")
	for route in ipRouteTable_dict:
                routes.append({
			"ipRouteDest"      : ipRouteTable_dict[route]["ipRouteDest"],
			"ipRouteMask_cidr" : ipRouteTable_dict[route]["ipRouteMask_cidr"],
			"ipRouteMask"      : ipRouteTable_dict[route]["ipRouteMask"],
                        "ipRouteIfIndex"   : ifDesc_dict.get(ipRouteTable_dict[route]["ipRouteIfIndex"], ""),
                        "ipRouteProto"     : ipRouteTable_dict[route]["ipRouteProto"],
                        "ipRouteNextHop"   : ipRouteTable_dict[route]["ipRouteNextHop"],
			"ipRouteType"      : ipRouteTable_dict[route]["ipRouteType"],
                })

inv_info['switch_ipRoute'] = {
    "inv_function" : inv_switch_ipRoute,
#    'includes':  [ 'if_network.include' ],
    'snmp_info': [
        ( ".1.3.6.1.2.1", [
           "2.2.1.1",            # ifIndex
           "2.2.1.2",            # ifDescr
           "31.1.1.1.18",        # ifAlias
           "2.2.1.3",            # ifType
        ]),
	(".1.3.6.1.2.1.4.21",                 [OID_END, "1"]),
    ],
    'snmp_scan_function': lambda oid: oid(".1.3.6.1.2.1.4.21.1.*") != None and oid(".1.3.6.1.2.1.4.24.4.*") == None,
}

