#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2010             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Andre Eckstein <Andre.Eckstein@Bechtle.com>
# updated by Christian Burmeister 10/2015

def inventory_qnap_info(checkname, info):
#    import pprint; pprint.pprint(info)
    return [(None, None, None)]

def check_qnap_info(item, no_params, info):
    try:
        uptime = int(info[0][2])
        uptime = uptime / 360000
        return (0, "%s -- Serial Nr.: %s -- Uptime: %s hours" % (info[0][0], info[0][1], uptime ))
        print "test"
    except:
        return (3, "UNKNOWN - No SNMP Output from Agent")

check_info['qnap_info'] = (check_qnap_info, "QNAP Info", 0, inventory_qnap_info)

snmp_info['qnap_info'] = ( ".1.3.6.1", [ "2.1.1.1.0", "2.1.47.1.1.1.1.11.1", "2.1.25.1.1.0" ] )
snmp_scan_functions['qnap_info'] = \
    lambda oid: "QNAP Systems" in oid('.1.3.6.1.2.1.47.1.1.1.1.12.1')
