#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2010             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Andre Eckstein <Andre.Eckstein@Bechtle.com>
# updated by Christian Burmeister 10/2015

qnap_temp_default_levels = (55, 60) 

def inventory_qnap_temp(checkname, info):

    inventory = []
    if "C/" in  info[0][0]:
	inventory.append(("Temperature System", "", "qnap_temp_default_levels" ))
    if "C/" in  info[0][1]:
	inventory.append(("Temperature CPU", "", "qnap_temp_default_levels" ))
    return inventory
    
def check_qnap_temp(item, params, info):
    warn, crit = params
    temp = ""

    for line in info:
        if item == "Temperature System":
            temp = info[0][0]
        elif item == "Temperature CPU":
            temp = info[0][1]

        temp = temp.split("/")
        temp = temp[0]
        temp = temp.rsplit(" C")
        temp = int(temp[0])

        perfdata = [("temp", temp, warn, crit)]
	infotext = " %s is at %sC (levels at %s/%s)" % ( item, temp, warn, crit )

        if temp >= crit:
            return (2, "Critical - " + infotext, perfdata )
        elif temp >= warn:
            return (1, "Warning - " + infotext, perfdata )  
        else:
            return (0, "OK - " + infotext, perfdata)
    return (3, "UNKNOWN", [])

check_info['qnap_temp'] = (check_qnap_temp, "QNAP %s", 1, inventory_qnap_temp)

snmp_info['qnap_temp'] = ( ".1.3.6.1.4.1.24681.1.2", ["5", "6"] )
snmp_scan_functions['qnap_temp'] = \
    lambda oid: "QNAP Systems" in oid('.1.3.6.1.2.1.47.1.1.1.1.12.1')
