#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.





def inventory_cisco_asa_connections(info):
    if len(info) == 1:
	if len(info[0]) == 2:
	   return [(None,None)]
    return []


def check_cisco_asa_connections(item, params, info):

    pixsessions = info[0][0]
    pixMaxSessions = info[0][1]

    state = 0
    msgtxt = "Anzahl der aktuellen IP-Connections %s, Hoechste Anzahl seit Systemstart %s" % (pixsessions, pixMaxSessions)
    perfdata = [("pixsessions", pixsessions), ("pixMaxSessions", pixMaxSessions)]
    return (state, msgtxt, perfdata)


check_info["cisco_asa_connections"]  = {
    "check_function"     : check_cisco_asa_connections,
    "inventory_function" : inventory_cisco_asa_connections,
    "service_description": "ASA Connections",
    "has_perfdata"       : True,
    "snmp_scan_function" : lambda oid: oid(".1.3.6.1.2.1.1.1.0").lower().startswith("cisco adaptive security"),
    "snmp_info"          : (".1.3.6.1.4.1.9.9.147.1.2.2.2.1.5.40", [
         	"6", # PixSessions
         	"7", # PixMaxSessions
        ]),
}
